name: Build Gradle APP

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK for the APP
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Use Gradle wrapper as executable
      run: chmod +x ./gradlew
      
    - name: Build the Program with Gradle
      run: ./gradlew build