name: Build gradle-hello-world-multistage-docker APP

on:
  push:
    branches: 
      - task4
  workflow_dispatch:
  

jobs:
  Task_change_code_and_change_ver_two:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Hello World to Hello World Avicii
      run: |
        FILE_PATH="src/main/java/com/ido/HelloWorld.java"
        SEARCH_STRING="System.out.println(\"Hello World!\");"
        REPLACE_STRING="System.out.println(\"Hello World Avicii!\");"

        if [ ! -f "$FILE_PATH" ]; then
          echo "Error: File $FILE_PATH does not exist"
          exit 1
        fi

        sed -i "s/$SEARCH_STRING/$REPLACE_STRING/g" "$FILE_PATH"

    - name: Extract version from gradle.properties
      run: |
        VERSION=$(grep "^project.version=" gradle.properties | sed -E 's/project.version=//')
        echo "Extracted version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV


        - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Multistage Docker image
      run: |
        REPO_NAME=${{ github.event.repository.name }}

        docker build --build-arg REPO_NAME=${REPO_NAME} -t ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ env.VERSION }} .
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ env.VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest

        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest

    - name: Increment Version in gradle.properties
      run: |
        VERSION=$(grep "^project.version=" gradle.properties | sed -E 's/project.version=//')
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$patch"
        echo "New version: $NEW_VERSION"
        sed -i "s/^project.version=.*/project.version=$NEW_VERSION/" gradle.properties  
    
    - name: Commit and Push Version Update
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.name "avichai"
        git config --global user.email "avichai321@git.com"
        git add gradle.properties
        git commit -m "Auto-incremented version to $VERSION" || echo "No changes to commit"
        # Use PAT for authentication
        git push https://x-access-token:${GIT_TOKEN}@github.com/${{ github.repository }}.git task4 || echo "No changes to push"

    
