name: Task4 Build Gradle app with Multistage Docker

on:
  push:
    branches:
      - task4

jobs:
  Update_build_push_run:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Increment Version in build.gradle.kts
      run: |
        VERSION=$(grep -oP 'version\s*=\s*"\K[^"]*' build.gradle.kts)
        echo "Current version: $VERSION"
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$patch"
        sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" build.gradle.kts
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"

    - name: Build Docker Image with Updated Version
      run: |
        REPO_NAME=${{ github.event.repository.name }}
        docker build --build-arg REPO_NAME=${REPO_NAME} -t ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${NEW_VERSION} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Tag and Push Docker Image with Updated Version
      run: |
        REPO_NAME=${{ github.event.repository.name }}
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${NEW_VERSION} ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:${NEW_VERSION}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${REPO_NAME}:latest

    - name: Pull updated image from Docker hub and run
      run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ NEW_VERSION }}
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ NEW_VERSION }}
